services:
  api:
    networks:
      - default
      - eth_archive_node

  worker:
    networks:
      - default
      - eth_archive_node


networks:
  eth_archive_node:
    external: true
    name: eth-archive-node_default
