-- The serving and indexing paths use bigname_phase exclusively. Keep the
-- SQLx migration ledger and extension-owned public objects, but retire every
-- bigname table from the legacy public-schema runtime in one dependency-safe
-- operation.
DROP TABLE IF EXISTS
    public.address_names_current,
    public.address_names_current_identity_counts,
    public.address_names_current_identity_feed,
    public.backfill_coverage_facts,
    public.backfill_jobs,
    public.backfill_ranges,
    public.base_normalized_rederive_run_batches,
    public.base_normalized_rederive_runs,
    public.chain_checkpoints,
    public.chain_header_audit,
    public.chain_lineage,
    public.chain_lineage_mutation_revision_evidence,
    public.chain_lineage_mutation_revisions,
    public.children_current,
    public.contract_instance_addresses,
    public.contract_instances,
    public.current_projection_full_replay_input_revision,
    public.current_projection_replay_attempt,
    public.current_projection_replay_status,
    public.current_projection_staging_checkpoints,
    public.discovery_admission_epochs,
    public.discovery_edges,
    public.event_silent_resolver_call_observations,
    public.execution_cache_outcomes,
    public.execution_steps,
    public.execution_traces,
    public.full_closure_coverage_input_changes,
    public.full_closure_coverage_input_revisions,
    public.full_closure_coverage_rollup_states,
    public.full_closure_coverage_rollups,
    public.label_preimage_backfill_runs,
    public.label_preimages,
    public.manifest_alert_observations,
    public.manifest_capability_flags,
    public.manifest_contract_instances,
    public.manifest_discovery_rules,
    public.manifest_versions,
    public.name_current,
    public.name_surface_normalization_repair_findings,
    public.name_surfaces,
    public.normalized_events,
    public.normalized_replay_adapter_checkpoint_items,
    public.normalized_replay_adapter_checkpoints,
    public.normalized_replay_coverage_recovery_epochs,
    public.normalized_replay_coverage_recovery_failures,
    public.normalized_replay_coverage_recovery_job_attempts,
    public.normalized_replay_cursors,
    public.permissions_current,
    public.permissions_current_publication,
    public.permissions_current_resource_summary,
    public.primary_names_current,
    public.projection_apply_cursors,
    public.projection_direct_invalidation_revisions,
    public.projection_invalidation_dead_letters,
    public.projection_invalidations,
    public.projection_normalized_event_changes,
    public.projection_permissions_resource_input_revisions,
    public.raw_call_snapshots,
    public.raw_code_hashes,
    public.raw_log_staging_block_revisions,
    public.raw_log_staging_input_revisions,
    public.raw_logs,
    public.raw_payload_cache_metadata,
    public.raw_receipts,
    public.raw_transactions,
    public.record_inventory_current,
    public.resolver_current,
    public.resolver_profile_authority_journal,
    public.resolver_profile_authority_journal_entries,
    public.resolver_profile_input_changes,
    public.resolver_profile_reconciliation_invalidation_keys,
    public.resolver_profile_reconciliation_runs,
    public.resolver_profile_reconciliation_state_items,
    public.resolver_profile_reconciliation_targets,
    public.resources,
    public.service_loop_heartbeats,
    public.stored_lineage_coverage_frontier_requirements,
    public.stored_lineage_coverage_frontiers,
    public.surface_bindings,
    public.token_lineages
CASCADE;

-- Table-owned triggers disappear above, but PostgreSQL does not record the
-- table references inside these legacy PL/pgSQL bodies as dependencies. Drop
-- the callable surface explicitly so no dead public-schema database API
-- survives the cutover.
DROP FUNCTION IF EXISTS
    public.address_names_current_identity_count_decrement(text, text),
    public.address_names_current_identity_count_increment(text, text),
    public.address_names_current_identity_counts_apply_delete(text, text, text),
    public.address_names_current_identity_counts_apply_delete(text, text, text, uuid, uuid, uuid),
    public.address_names_current_identity_counts_apply_insert(text, text, text),
    public.address_names_current_identity_counts_apply_insert(text, text, text, uuid, uuid, uuid),
    public.address_names_current_identity_counts_lock_address(text),
    public.address_names_current_identity_counts_lock_pair(text, text),
    public.address_names_current_identity_counts_recompute_address(text),
    public.address_names_current_identity_counts_recompute_for_binding(),
    public.address_names_current_identity_counts_recompute_for_name_curren(),
    public.address_names_current_identity_counts_recompute_for_resource(),
    public.address_names_current_identity_counts_recompute_for_surface(),
    public.address_names_current_identity_counts_recompute_for_token_linea(),
    public.address_names_current_identity_counts_trigger(),
    public.address_names_current_identity_feed_address_trigger(),
    public.address_names_current_identity_feed_binding_trigger(),
    public.address_names_current_identity_feed_candidate_rows(text),
    public.address_names_current_identity_feed_name_current_trigger(),
    public.address_names_current_identity_feed_primary_trigger(),
    public.address_names_current_identity_feed_recompute_address(text),
    public.address_names_current_identity_feed_recompute_for_bindings(uuid[]),
    public.address_names_current_identity_feed_recompute_for_logical_names(text[]),
    public.address_names_current_identity_feed_recompute_for_resources(uuid[]),
    public.address_names_current_identity_feed_recompute_for_token_lineage(uuid[]),
    public.address_names_current_identity_feed_resource_trigger(),
    public.address_names_current_identity_feed_token_lineage_trigger(),
    public.address_names_current_identity_readable_relation_rows(text),
    public.address_names_current_identity_row_readable(text, uuid, uuid, uuid),
    public.address_names_current_identity_visible_relation_count(text, text, text),
    public.advance_projection_invalidation_generation_after_dead_letter(),
    public.anc_counts_bindings_stmt_trigger(),
    public.anc_counts_name_surfaces_stmt_trigger(),
    public.anc_counts_resources_stmt_trigger(),
    public.anc_counts_token_lineages_stmt_trigger(),
    public.anc_feed_bindings_stmt_trigger(),
    public.anc_feed_name_surfaces_stmt_trigger(),
    public.anc_feed_resources_stmt_trigger(),
    public.anc_feed_token_lineages_stmt_trigger(),
    public.anc_identity_counts_recompute_bindings(uuid[]),
    public.anc_identity_counts_recompute_logical_names(text[]),
    public.anc_identity_counts_recompute_resources(uuid[]),
    public.anc_identity_counts_recompute_token_lineages(uuid[]),
    public.bigname_invalidate_verified_primary_name_tuple(text, text, text),
    public.bigname_lock_primary_name_anchor(text, text, text),
    public.bigname_primary_name_tuple_lock_key(text, text, text),
    public.bigname_primary_names_current_fence_before_write(),
    public.bigname_primary_names_current_invalidate_after_write(),
    public.bigname_primary_names_current_replacement_lock_key(),
    public.bump_chain_lineage_mutation_revision_after_delete(),
    public.bump_chain_lineage_mutation_revision_after_insert(),
    public.bump_chain_lineage_mutation_revision_after_update(),
    public.bump_raw_log_staging_revision_after_delete(),
    public.bump_raw_log_staging_revision_after_insert(),
    public.bump_raw_log_staging_revision_after_update(),
    public.capture_projection_direct_invalidation_watermark(),
    public.capture_projection_normalized_event_change_watermark(),
    public.capture_projection_permissions_resource_input_watermark(),
    public.enforce_current_projection_replay_version_fence(),
    public.identity_canonicality_readability_changed(public.canonicality_state, public.canonicality_state),
    public.identity_canonicality_readable(public.canonicality_state),
    public.journal_full_closure_coverage_fact_deletes(),
    public.journal_full_closure_coverage_fact_inserts(),
    public.journal_full_closure_coverage_fact_truncate(),
    public.journal_full_closure_coverage_fact_updates(),
    public.journal_full_closure_coverage_job_authority_updates(),
    public.mark_raw_log_staging_incomplete_after_truncate(),
    public.queue_resolver_profile_input_changes_after_raw_code_insert(),
    public.queue_resolver_profile_input_changes_after_raw_code_update(),
    public.queue_surface_binding_repair_projection_invalidations(),
    public.record_projection_direct_invalidation_revision(),
    public.record_projection_normalized_event_change(),
    public.record_projection_permissions_resource_input_revision(),
    public.record_resolver_profile_input_changes(jsonb),
    public.reset_projection_invalidation_retry_state();

DROP SEQUENCE IF EXISTS
    public.projection_direct_invalidation_revision_seq,
    public.projection_permissions_resource_input_revision_seq;

DROP TYPE IF EXISTS
    public.backfill_lifecycle_status,
    public.canonicality_state,
    public.capability_support_status,
    public.manifest_rollout_status,
    public.projection_invalidation_state
CASCADE;
