[package]
name = "bigname-project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
bigname-domain.workspace = true
bigname-execution.workspace = true
bigname-storage.workspace = true
serde_json = "1.0.149"
sqlx.workspace = true

[dev-dependencies]
serde_json = "1.0.149"
