[package]
name = "bigname-interpret"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bigname-adapters = { path = "../adapters", default-features = false, features = ["schema-v2"] }
bigname-domain.workspace = true
serde_json = "1.0.149"
sqlx = { workspace = true, features = ["time"] }
time = { version = "0.3.47", features = ["serde"] }
