//! Frozen encoding shared by the Project history catalogue and its reader. These summaries
//! prove only negative matches; exact filters and attribution still decide every event.

/// Real block buckets are nonnegative. -1 is the separate unpositioned bucket, before every
/// block ascending and after every block descending, matching the public null placement.
pub const NULL_BUCKET: i64 = -1;
pub const BUCKET_BLOCKS: i64 = 256;
pub const CATALOGUE_VERSION: i16 = 1;
pub const NAME: i16 = 0;
pub const RESOURCE: i16 = 1;
pub const NODE: i16 = 2;
pub const RECORD_ID: i16 = 3;
pub const TOKEN_HOLDER: i16 = 1;
pub const EFFECTIVE_CONTROLLER: i16 = 2;
pub const ROLE_HOLDER: i16 = 4;

/// Bit positions are append-only. An unknown event kind sets every bit and cannot be pruned.
const EVENT_KINDS: &[&str] = &[
    "AccountPermissionChanged",
    "AliasChanged",
    "AuthorityEpochChanged",
    "AuthorityTransferred",
    "ContractDiscovered",
    "ExpiryChanged",
    "MigrationApplied",
    "ParentChanged",
    "PermissionChanged",
    "PermissionScopeChanged",
    "PreimageObserved",
    "RecordChanged",
    "RecordVersionChanged",
    "RegistrarNameRegistered",
    "RegistrationGranted",
    "RegistrationReleased",
    "RegistrationRenewed",
    "RegistrationReserved",
    "RegistryCreated",
    "ResolverChanged",
    "ResolverPermissionArgument",
    "ResolverRecordLinked",
    "ReverseChanged",
    "RootPermissionChanged",
    "SourceManifestUpdated",
    "SubregistryChanged",
    "SurfaceBound",
    "SurfaceUnbound",
    "TokenControlTransferred",
    "TokenRegenerated",
    "TokenResourceLinked",
    "Upgraded",
];

pub fn event_kind_mask(kind: &str) -> i64 {
    EVENT_KINDS
        .iter()
        .position(|candidate| *candidate == kind)
        .map_or(i64::MAX, |index| 1_i64 << index)
}

pub fn relation_mask(relation: &str) -> i16 {
    match relation {
        "token_holder" => TOKEN_HOLDER,
        "effective_controller" => EFFECTIVE_CONTROLLER,
        "role_holder" => ROLE_HOLDER,
        _ => 0,
    }
}

/// `column` is trusted SQL generated by the caller, never request text.
pub fn event_kind_mask_sql(column: &str) -> String {
    let mut sql = format!("CASE {column}");
    for (index, kind) in EVENT_KINDS.iter().enumerate() {
        sql.push_str(&format!(" WHEN '{kind}' THEN {}::bigint", 1_i64 << index));
    }
    sql.push_str(&format!(" ELSE {}::bigint END", i64::MAX));
    sql
}

/// A 256-bit Bloom: four bit positions are the unsigned bytes 0, 5, 10 and 15 of MD5 over
/// the exact UTF-8 key. No folding or selector parsing. PostgreSQL's bit numbering is used
/// by both producer and reader, and collisions only cause extra exact probes.
/// `key` is a trusted SQL expression (a bound value for user input).
pub fn record_key_bloom_sql(key: &str) -> String {
    let mut sql = "B'0'::bit(256)".to_owned();
    for byte in [0, 5, 10, 15] {
        sql = format!("set_bit({sql}, get_byte(decode(md5({key}), 'hex'), {byte}), 1)");
    }
    sql
}

/// A reset matches every requested record key. Other kinds without a key cannot satisfy the
/// record-key predicate; unknown kinds remain conservative for a future vocabulary extension.
pub fn event_key_bloom_sql(alias: &str) -> String {
    let key = record_key_bloom_sql(&format!("{alias}.after_state ->> 'record_key'"));
    let known = EVENT_KINDS
        .iter()
        .map(|kind| format!("'{kind}'"))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "CASE WHEN {alias}.event_kind = 'RecordVersionChanged'
        OR {alias}.event_kind NOT IN ({known}) THEN B'1'::bit(256) | ~B'0'::bit(256)
        WHEN {alias}.event_kind = 'RecordChanged'
            AND {alias}.after_state ->> 'record_key' IS NOT NULL THEN {key}
        ELSE B'0'::bit(256) END"
    )
}
