[package]
name = "phase-runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

bigname-content-hash.workspace = true
bigname-execution.workspace = true
bigname-ingest = { workspace = true, features = ["reth-db"] }
bigname-interpret.workspace = true
bigname-manifests.workspace = true
bigname-project.workspace = true
bigname-storage.workspace = true

[dev-dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
axum.workspace = true
bigname-test-support.workspace = true
serde_json = "1.0.149"
