[package]
name = "bigname-content-hash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
build = "build.rs"

[dependencies]
alloy-primitives.workspace = true

[build-dependencies]
alloy-primitives.workspace = true

[dev-dependencies]
proc-macro2 = { version = "1.0.106", features = ["span-locations"] }
syn = { version = "2.0.117", features = ["full", "visit"] }
